# Alembic Migration Script Template

"""Initial database schema.

Revision ID: 001
Revises: 
Create Date: 2024-01-17 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Run migration upgrades."""
    # This will be auto-generated by: alembic revision --autogenerate -m "message"
    pass


def downgrade() -> None:
    """Run migration downgrades."""
    pass
